### ISSUE TITLE
Crash when acquiring GPS

### ISSUE THREAD

**Issue by twyatt** [twyatt/sdsu-rocket#4]
Apr 10, 2015 6:48:37 PM net.sf.marineapi.nmea.io.SentenceReader fireSentenceEvent
WARNING: Exception caught from SentenceListener
java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
	at java.util.ArrayList.rangeCheck(ArrayList.java:638)
	at java.util.ArrayList.get(ArrayList.java:414)
	at net.sf.marineapi.nmea.parser.SentenceParser.getStringValue(SentenceParser.java:420)
	at net.sf.marineapi.nmea.parser.GSVParser.getSatelliteInfo(GSVParser.java:87)
	at net.sf.marineapi.provider.SatelliteInfoProvider.createProviderEvent(SatelliteInfoProvider.java:65)
	at net.sf.marineapi.provider.SatelliteInfoProvider.createProviderEvent(SatelliteInfoProvider.java:39)
	at net.sf.marineapi.provider.AbstractProvider.sentenceRead(AbstractProvider.java:217)
	at net.sf.marineapi.nmea.io.SentenceReader.fireSentenceEvent(SentenceReader.java:197)
	at net.sf.marineapi.nmea.io.AbstractDataReader.run(AbstractDataReader.java:86)
	at java.lang.Thread.run(Thread.java:744)

...

Apr 10, 2015 6:48:46 PM net.sf.marineapi.nmea.io.SentenceReader fireSentenceEvent
WARNING: Exception caught from SentenceListener
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:638)
	at java.util.ArrayList.get(ArrayList.java:414)
	at net.sf.marineapi.nmea.parser.SentenceParser.getStringValue(SentenceParser.java:420)
	at net.sf.marineapi.nmea.parser.SentenceParser.getCharValue(SentenceParser.java:365)
	at net.sf.marineapi.nmea.parser.RMCParser.getStatus(RMCParser.java:133)
	at net.sf.marineapi.provider.PositionProvider.isValid(PositionProvider.java:123)
	at net.sf.marineapi.provider.AbstractProvider.validate(AbstractProvider.java:239)
	at net.sf.marineapi.provider.AbstractProvider.sentenceRead(AbstractProvider.java:216)
	at net.sf.marineapi.nmea.io.SentenceReader.fireSentenceEvent(SentenceReader.java:197)
	at net.sf.marineapi.nmea.io.AbstractDataReader.run(AbstractDataReader.java:86)
	at java.lang.Thread.run(Thread.java:744)

**Comment by twyatt** [comment]
Fixed by upgrading MarineAPI to 0.9.0-SNAPSHOT.
