### ISSUE TITLE
crash yo

### ISSUE THREAD

**Issue by mcwrenn21** [twyatt/sdsu-rocket#5]
login as: pi
pi@192.168.1.127's password:
Linux yagi 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Apr 10 20:52:01 2015 from mac-think.lan
pi@yagi ~ $ sudo screen -r
/home/pi/start.sh
# + set -e
+ gpio mode '{SHDN}' out
+ gpio write '{SHDN}' 0
+ cd /home/pi/server/
+ java -jar server.jar
Starting application.
Loading Settings: settings.json
Setup Logging.
Logging started at 14558030119.
Setup Accelerometer [ADXL345].
Exception in thread "main" java.io.IOException: Error writing to /dev/i2c-1 at address 0x53 to address 0x2d. Got -20001.
        at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:122)
        at edu.sdsu.rocket.pi.devices.ADXL345.setup(ADXL345.java:228)
        at edu.sdsu.rocket.server.Application.setupAccelerometer(Application.java:168)
        at edu.sdsu.rocket.server.Application.setupDevices(Application.java:155)
        at edu.sdsu.rocket.server.Application.setup(Application.java:109)
        at edu.sdsu.rocket.server.Launcher.main(Launcher.java:17)
#

**Comment by twyatt** [comment]
This was determined to be an issue with the I2C not being ready on the Pi in time during startup.

Could try adding a delay to the starting of the server or add support for multiple start attempts in the startup script.
